### ISSUE TITLE
[Tracking] `.api` based type definitions

### ISSUE THREAD

**Issue by nikithauc** [microsoftgraph/msgraph-sdk-javascript#1022]
- [ ] Ship typings package supporting `.api`-based type definitions. Modify [Graph types](https://www.npmjs.com/package/@microsoft/microsoft-graph-types)
- [ ]  Split the Graph API surface to smaller modules using module augmentation.
- [ ] Raptor for `api-based` type definitions
